In [1]:
# Import the dependencies
import pandas as pd
import numpy as np

In [2]:
mortality_data = pd.read_csv("cleaned_data/data_by_country.csv")
mortality_data.head()

,Unnamed: 0,Country,Literacy_Rate,Buddhists,Christians,Folk_Religions,Hindus,Jews,Muslims,Other_Religions,...,gpd_2010,gpd_2015,gdp_per_capita_2000,gdp_per_capita_2005,gdp_per_capita_2010,gdp_per_capita_2015,mortality_rate_2000,mortality_rate_2005,mortality_rate_2010,mortality_rate_2015
0,0,Albania,96.8,1.0,18.0,1.0,1.0,1.0,80.3,1.0,...,1.192692e+10,1.138685e+10,1126.683340,2673.786584,4094.348386,3952.802538,106.1,105.7,103.5,92.24
1,1,Algeria,72.6,1.0,1.0,1.0,1.0,1.0,97.9,1.0,...,1.612073e+11,1.659793e+11,1765.027146,3113.094883,4480.786318,4177.889542,141.9,119.3,104.4,96.49
2,2,Angola,70.4,1.0,90.5,4.2,1.0,1.0,1.0,1.0,...,8.169956e+10,8.721929e+10,556.836182,1902.422150,3497.974488,3127.890598,383.6,322.7,269.7,239.80
3,3,Antigua and Barbuda,99.0,1.0,93.0,3.6,1.0,1.0,1.0,1.0,...,1.148700e+09,1.336693e+09,10872.292952,12557.547850,13048.960582,14285.329777,156.7,156.1,134.6,121.90
4,4,Argentina,97.9,1.0,85.2,1.0,1.0,1.0,1.0,1.0,...,4.236274e+11,5.947493e+11,7708.099115,5109.852245,10385.964432,13789.060425,138.5,124.9,118.7,112.70

In [3]:
country = mortality_data[['Country']]
country_df = pd.DataFrame(country)
country_df

                 Country
0                Albania
1                Algeria
2                 Angola
3    Antigua and Barbuda
4              Argentina
..                   ...
134              Uruguay
135           Uzbekistan
136              Vanuatu
137               Zambia
138             Zimbabwe

[139 rows x 1 columns]

In [4]:
from geopy.exc import GeocoderTimedOut
from geopy.geocoders import Nominatim

In [5]:
# used code from https://www.geeksforgeeks.org/how-to-find-longitude-and-latitude-for-a-list-of-regions-or-country-using-python/

# declare an empty list to store
# latitude and longitude of values 
# of city column
longitude = []
latitude = []
   
# function to find the coordinate
# of a given city 
def findGeocode(country):
       
    # try and catch is used to overcome
    # the exception thrown by geolocator
    # using geocodertimedout  
    try:
          
        # Specify the user_agent as your
        # app name it should not be none
        geolocator = Nominatim(user_agent="Mort_Pred")
          
        return geolocator.geocode(country)
      
    except GeocoderTimedOut:
          
        return findGeocode(country)    
  
# each value from city column
# will be fetched and sent to
# function find_geocode   
for i in (country_df["Country"]):
      
    if findGeocode(i) != None:
           
        loc = findGeocode(i)
          
        # coordinates returned from 
        # function is stored into
        # two separate list
        latitude.append(loc.latitude)
        longitude.append(loc.longitude)
       
    # if coordinate for a city not
    # found, insert "NaN" indicating 
    # missing value 
    else:
        latitude.append(np.nan)
        longitude.append(np.nan)

In [10]:
pd.set_option('display.max_rows', 200)
# now add this column to dataframe
country_df["Longitude"] = longitude
country_df["Latitude"] = latitude
  
country_df

                      Country   Longitude   Latitude
0                     Albania   19.999962  41.000028
1                     Algeria    2.999983  28.000027
2                      Angola   17.569124 -11.877577
3         Antigua and Barbuda  -61.955461  17.223472
4                   Argentina  -64.967282 -34.996496
5                     Armenia   44.673665  40.769627
6                   Australia  134.755000 -24.776109
7                     Austria   14.124560  47.593970
8                  Azerbaijan   47.787251  40.393629
9                     Bahrain   50.534461  26.155125
10                 Bangladesh   90.293441  24.476929
11                   Barbados  -59.525030  13.150033
12                    Belarus   27.697136  53.425061
13                    Belgium    4.666715  50.640281
14                     Belize  -88.760093  16.825979
15                      Benin    2.258441   9.529347
16                     Bhutan   90.511927  27.549511
17                   Botswana   24.592874 -23.168178
18                     Brazil  -53.200000 -10.333333
19                   Bulgaria   25.485662  42.607397
20               Burkina Faso   -1.688031  12.075308
21                    Burundi   29.932452  -3.426449
22                   Cambodia  104.814491  12.543322
23                   Cameroon   13.153581   4.612552
24   Central African Republic   19.998123   7.032360
25                       Chad   19.015617  15.613414
26                      Chile  -71.318770 -31.761336
27                      China  104.999927  35.000074
28                   Colombia  -72.908813   4.099917
29                    Comoros   44.283296 -12.204518
30                 Costa Rica  -84.073910  10.273563
31                    Croatia   17.011895  45.564344
32                       Cuba  -80.832875  23.013134
33                     Cyprus   33.145128  34.982302
34                    Denmark   10.333328  55.670249
35                   Djibouti   42.845306  11.814597
36         Dominican Republic  -70.302803  19.097403
37                    Ecuador  -79.366697  -1.339767
38                El Salvador  -88.914068  13.800038
39          Equatorial Guinea   10.517036   1.613172
40                    Estonia   25.331908  58.752378
41                   Ethiopia   38.652120  10.211670
42                       Fiji  179.012274 -18.123970
43                    Finland   25.920916  63.246778
44                     France    1.888334  46.603354
45                      Gabon   11.689970  -0.899969
46                    Georgia  -83.113737  32.329381
47                    Germany   10.447831  51.163818
48                      Ghana   -1.080027   8.030028
49                     Greece   21.987713  38.995368
50                    Grenada  -61.690404  12.136037
51                  Guatemala  -90.345759  15.585555
52                     Guinea  -10.708359  10.722623
53              Guinea-Bissau  -14.900021  12.100035
54                     Guyana  -58.641689   4.841710
55                      Haiti  -72.357097  19.139995
56                   Honduras  -86.075514  15.257243
57                    Hungary   19.506094  47.181759
58                    Iceland  -18.105901  64.984182
59                      India   78.667743  22.351115
60                  Indonesia  117.890285  -2.483383
61                       Iraq   44.174977  33.095579
62                    Ireland   -7.979460  52.865196
63                     Israel   34.859476  30.812425
64                      Italy   12.674297  42.638426
65                    Jamaica  -77.394769  18.185051
66                      Japan  139.239418  36.574844
67                     Jordan   36.941628  31.166705
68                 Kazakhstan   66.778082  48.101295
69                      Kenya   38.431398   1.441968
70                     Kuwait   47.497948  29.273396
71                     Latvia   24.753764  56.840649
72                    Lebanon   35.843409  33.875063
73                    Lesotho   28.335019 -29.603927
74                    Liberia   -9.365852   5.749972
75                      Libya   18.123672  26.823447
76                  Lithuania   23.750000  55.350000
77                 Luxembourg    6.129675  49.815868
78                 Madagascar   46.441642 -18.924960
79                     Malawi   33.930196 -13.268720
80                   Malaysia  102.265682   4.569375
81                   Maldives   73.224415   3.720350
82                       Mali   -2.290024  16.370036
83                      Malta   14.447691  35.888599
84                 Mauritania   -9.239926  20.254038
85                  Mauritius   57.570357 -20.275945
86                     Mexico -102.007710  23.658512
87                   Mongolia  103.849974  46.825039
88                    Morocco   -7.336248  31.172821
89                 Mozambique   34.914498 -19.302233
90                    Namibia   17.323111 -23.233550
91                      Nepal   84.091714  28.108393
92                Netherlands    5.634323  52.243498
93                New Zealand  172.834408 -41.500083
94                  Nicaragua  -85.293691  12.609016
95                      Niger    9.323843  17.735621
96                    Nigeria    7.999972   9.600036
97                     Norway    9.099972  60.500021
98                       Oman   57.003690  21.000029
99                   Pakistan   71.247499  30.330840
100                    Panama  -81.130843   8.559559
101          Papua New Guinea  144.248908  -5.681607
102                  Paraguay  -58.169345 -23.316593
103                      Peru  -75.045851  -6.869970
104               Philippines  122.731210  12.750349
105                    Poland   19.134422  52.215933
106                  Portugal   -7.889626  40.033263
107                     Qatar   51.229529  25.333698
108                   Romania   24.685923  45.985213
109                    Rwanda   30.064436  -1.964663
110                     Samoa -172.120050 -13.769390
111              Saudi Arabia   42.352833  25.624262
112                   Senegal  -14.452961  14.475061
113                Seychelles   55.454015  -4.657498
114              Sierra Leone  -11.840027   8.640035
115                 Singapore  103.819499   1.357107
116                  Slovenia   14.480837  45.813311
117           Solomon Islands  159.107069  -8.705394
118              South Africa   24.991639 -28.816624
119                     Spain   -4.837979  39.326068
120                 Sri Lanka   80.713785   7.555494
121                  Suriname  -56.077119   4.141303
122                    Sweden   14.520858  59.674971
123               Switzerland    8.231974  46.798562
124                Tajikistan   70.815654  38.628173
125                  Thailand  100.832730  14.897192
126                      Togo    1.019977   8.780026
127                     Tonga -175.202642 -19.916082
128       Trinidad and Tobago  -61.084007  10.746690
129                   Tunisia    9.400138  33.843941
130              Turkmenistan   59.392461  39.376381
131                    Uganda   32.216658   1.533355
132                   Ukraine   31.271832  49.487197
133      United Arab Emirates   53.999483  24.000249
134                   Uruguay  -56.020153 -32.875555
135                Uzbekistan   63.952810  41.323730
136                   Vanuatu  168.106915 -16.525507
137                    Zambia   27.558988 -14.518912
138                  Zimbabwe   29.746841 -18.455496

In [7]:
country_df.count()

Country      139
Longitude    139
Latitude     139
dtype: int64

In [8]:
country_df.isnull().sum()

Country      0
Longitude    0
Latitude     0
dtype: int64

In [12]:
country_df.to_csv('Coordinates.csv')